### ISSUE TITLE
The background color before display.

### ISSUE THREAD

**Issue by blackredscarf** [entronad/flutter_echarts#23] opened 2020-03-30 10:34 UTC
Though I set the background color, background color before display is white on a tick. If my app background is no white, even is black, it will be disharmony.

尽管设置了背景颜色，但在视图显示之前，会有一瞬间的白色。如果我的APP背景颜色不是白色，甚至是黑色，将导致严重的色差冲突。

**Comment by entronad** [comment] 2020-03-30 11:45
This is caused by the forced white background of webview in webview_flutter plugin. Now we don't have any workaround to avoid the white blink before the chart is loaded. Many people are following this issue of webview_flutter: https://github.com/flutter/flutter/issues/29300
We hope this will be fixed soon.

这是由于 webview_flutter 强制 webview 的背景颜色为白色（而不是透明），
目前没有好的办法解决因此导致的加载完成前一瞬间的白色，很多人也在跟进 webview_flutter 的这个问题：https://github.com/flutter/flutter/issues/29300
希望在下个版本中会改进

**Comment by blackredscarf** [comment] 2020-03-30 12:02
@entronad 
OK. My temporary solution is to use Opacity to making Echarts invisiable, and waiting a tick when Echarts starts to render, after that making Echarts visiable.
```dart
Opacity(
  opacity: opacity,
  child: Container(
	child: Echarts(
	  key: chartKey,
	  onMessage: (emsg) {
		if(emsg == 'rendered') {
		  if(opacity == 0) {  // wait the render of chart
			Future.delayed(Duration(milliseconds: 50), () {
			  opacity = 1;
                          setState({});
			  // or bloc.add();
			});
		  }
		}
	  },
	  extraScript: '''
		  chart.on('rendered', () => {
			Messager.postMessage('rendered');
		  });
		''',
```

**Comment by entronad** [comment] 2020-03-31 01:07
@blackredscarf 
Dose this work on iOS?
We have thought about this way, but according to my experiment and this user's case: https://github.com/entronad/flutter_echarts/issues/18#issuecomment-603812411 , echarts dosen't work well in Opacity.

**Comment by blackredscarf** [comment] 2020-04-01 11:54
@entronad 
I only test it on Android now. I will have a try on iOS in a few month later.

**Closed** 2020-04-08 11:34 UTC

**Comment by hakaari** [comment] 2021-01-23 18:05
Wrapping chart with opacity doesn't work for me on iOS. A workaround I found is to use stack & cover the chart until is starts to render.

```
    Stack(
      children: [
        Echarts(
          option: data,
          onMessage: (message) {
            if (opacity == 1) {
              setState(() {
                opacity = 0.0;
              });
            }
          },
          extraScript: '''
  chart.on('rendered', function () {
    Messager.postMessage('chart rendered');
  });
''',
        ),
        Opacity(
          opacity: opacity,
          child: Container(
            color: Colors.black,
            width: MediaQuery.of(context).size.width,
            height: MediaQuery.of(context).size.height,
          ),
        )
      ],
    );

**Comment by volgin** [comment] 2021-02-26 16:54
You don't need opacity. Simply show a Container on top of a chart with an "if" statement. For example,

```
_hideChart = true;
...
return Stack(
        children: [
          Echarts(
            option: _dataString,
            extraScript: _extraScript,
            onMessage: (message) {
              if (mounted) {
                setState(() {
                  _hideChart = false;
                });
              }
            },
          ),
          if (_hideChart)
            Container(
              color: Colors.black,
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.height,
            ),
        ],
      );
```

This way you don't render an unnecessary widget with every refresh of a chart.
